version: '2.1'
orbs:
  ruby: circleci/ruby@1.8.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.6.9'
      - ruby/install-deps
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.6.9'
      - ruby/install-deps
      - run:
          name: 'Running test'
          command: bundle exec rake
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
